# Generated by Django 2.2.5 on 2019-12-31 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, null=True)),
                ('url', models.CharField(max_length=250, null=True)),
                ('logo', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sourcer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField()),
                ('url', models.CharField(max_length=125)),
                ('title', models.CharField(max_length=250)),
                ('excerpt', models.CharField(max_length=5000, null=True)),
                ('is_article', models.BooleanField()),
                ('has_video', models.BooleanField()),
                ('has_image', models.BooleanField()),
                ('word_count', models.CharField(max_length=8, null=True)),
                ('lang', models.CharField(max_length=3)),
                ('time_to_read', models.IntegerField(null=True)),
                ('top_image_url', models.CharField(default='https://ph-files.imgix.net/a3fc2bb8-9245-4f1b-b9c5-ba5888caad86', max_length=500, null=True)),
                ('listen_duration_estimate', models.IntegerField(null=True)),
                ('publisher_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Publisher')),
            ],
        ),
    ]
