# Generated by Django 2.2.5 on 2019-12-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userarticle',
            old_name='publishser_fk',
            new_name='publisher_fk',
        ),
    ]
