# Generated by Django 2.2.5 on 2020-01-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200101_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='read_status',
            field=models.CharField(default='DONE', max_length=255),
        ),
    ]
