# Generated by Django 2.2.5 on 2020-01-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userarticle_read_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField()),
                ('two', models.IntegerField()),
                ('three', models.IntegerField()),
                ('four', models.IntegerField()),
                ('five', models.IntegerField()),
            ],
        ),
    ]
