# Generated by Django 2.2.5 on 2020-01-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_prioritymatrix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriorityMatrix',
        ),
    ]
