# Generated by Django 2.2.5 on 2020-01-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_prioritymatrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_tag_timestamp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userarticle',
            name='tagged_timestamp',
            field=models.IntegerField(null=True),
        ),
    ]
