# Generated by Django 2.2.5 on 2020-01-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200112_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_tag_timestamp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userarticle',
            name='tagged_timestamp',
            field=models.FloatField(null=True),
        ),
    ]
