# Generated by Django 2.2.5 on 2020-01-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200112_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_tag_timestamp',
        ),
        migrations.RemoveField(
            model_name='userarticle',
            name='tagged_timestamp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tag_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userarticle',
            name='tag_number',
            field=models.IntegerField(default=0),
        ),
    ]
