# Generated by Django 2.2.5 on 2020-01-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200112_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userarticle',
            old_name='read_status',
            new_name='read_status_pocket',
        ),
    ]
