# Generated by Django 2.2.5 on 2020-01-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200116_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='read_status_incread',
            field=models.BooleanField(default=False),
        ),
    ]
